# Project-wide Gradle settings（由 Cocos Creator 模板补齐；路径可按本机修改）

org.gradle.jvmargs=-Xmx4608m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.injected.testOnly=false
android.native.buildOutput=verbose

PROP_COMPILE_SDK_VERSION=36
PROP_MIN_SDK_VERSION=22
PROP_TARGET_SDK_VERSION=36
PROP_BUILD_TOOLS_VERSION=36.0.0
PROP_APP_NAME=PetAI

PROP_ENABLE_INSTANT_APP=false

PROP_ENABLE_INPUTSDK=false

PROP_NDK_VERSION=23.1.7779620

PROP_ENABLE_COMPRESS_SO=true

PROP_IS_DEBUG=true

COCOS_ENGINE_PATH=C:/ProgramData/cocos/editors/Creator/3.8.8/resources/resources/3d/engine/native

RES_PATH=D:/UME_2026/PetAI-cocos/PetAI-cocos/build/android-003

NATIVE_DIR=D:/UME_2026/PetAI-cocos/PetAI-cocos/native/engine/android

APPLICATION_ID=com.ume.petai

PROP_APP_ABI=arm64-v8a
